# Generated by Django 5.0.6 on 2024-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='empty@gmail', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
